price=[70,65,80,90,45,75]
print(price)
total=sum(price)
print("total:",total)
highest=max(price)
print("highest:",highest)
lowest=min(price)
print("lowest:",lowest)
new_item=int(input("enter price:"))
price.append(new_item)
print(price)
cancel_order=int(input("enter cancelled order:"))
price.remove(cancel_order)
print("price:",price)
